### ISSUE TITLE
Unable to connect to Jack server (win experimental)

### ISSUE THREAD

**Issue by damiangr** [olegkapitonov/tubeAmp-Designer#2]
Hi , Thank you for this project. 
I'm trying to get winows wersion to run but I'm always getting "Unable to connect to Jack server" error.
Jack is installed and configured.
Could you advise?

Can you post build source for windows version?

Thank  you
Damian

**Comment by olegkapitonov** [comment]
Hi, Damian!
Thank you for your reply!

I added the source
https://github.com/olegkapitonov/tubeAmp-Designer/tree/win64

Windows version uses PortAudio to input/output sound instead of Jack.
I just forgot to change the error message :)

PortAudio tries to connect to the default input and output device.
https://github.com/olegkapitonov/tubeAmp-Designer/blob/c682ab80eea64225734574d15a46f4e1cdec4c7c/src/player.cpp#L468-L507

You may check whether your system has default input and output device,
you may also try to launch tube Amp Designer from the Windows command line
and look for error messages.

**Comment by damiangr** [comment]
olegkapitonov , Thank you for win sources!
In fact, the problem is with the sound settings in windows and the music interface settings. I had the sampling rate set to 48 kHz. When I switched to 44.1 kHz, the program started correctly.
